build: Fix cargo audit
Bump rustls to resolve the following issue:

 Crate:     rustls
 Version:   0.23.44
 Title:     TLS 1.3 handshake messages incorrectly accepted across
            encryption level boundaries
 ID:        RUSTSEC-2026-0285
 Severity:  5.3 (medium)
 Solution:  Upgrade to >=0.23.45
 error: 1 vulnerability found!

Signed-off-by: Bo Chen <bchen@crusoe.ai>